"""empty message

Revision ID: 43013b747b18
Revises: d0449b9f38c5
Create Date: 2024-08-06 18:19:07.033904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43013b747b18'
down_revision = 'd0449b9f38c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite')
    # ### end Alembic commands ###
