"""empty message

Revision ID: f3aab32946a1
Revises: 7d983fee48b7
Create Date: 2024-08-10 13:49:04.486658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3aab32946a1'
down_revision = '7d983fee48b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('opening_crawl', sa.Text(), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.Column('producer', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=50), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(length=50), nullable=True),
    sa.Column('crew', sa.String(length=50), nullable=True),
    sa.Column('passengers', sa.String(length=50), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=50), nullable=True),
    sa.Column('consumables', sa.String(length=50), nullable=True),
    sa.Column('vehicle_class', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_planets',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'planet_id')
    )
    op.create_table('film_starships',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'starship_id')
    )
    op.create_table('film_vehicles',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'vehicle_id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('hair_color', sa.String(length=50), nullable=True),
    sa.Column('skin_color', sa.String(length=50), nullable=True),
    sa.Column('eye_color', sa.String(length=50), nullable=True),
    sa.Column('birth_year', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('homeworld', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('average_height', sa.String(length=50), nullable=True),
    sa.Column('skin_colors', sa.String(length=255), nullable=True),
    sa.Column('hair_colors', sa.String(length=255), nullable=True),
    sa.Column('eye_colors', sa.String(length=255), nullable=True),
    sa.Column('average_lifespan', sa.String(length=50), nullable=True),
    sa.Column('homeworld', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['homeworld'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_people',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'person_id')
    )
    op.create_table('film_species',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'species_id')
    )
    op.create_table('people_species',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'species_id')
    )
    op.create_table('people_starships',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'starship_id')
    )
    op.create_table('people_vehicles',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'vehicle_id')
    )
    op.drop_table('starship_details')
    op.drop_table('characters')
    op.drop_table('character_details')
    op.drop_table('planet_details')
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('diameter', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('planets_name_key', type_='unique')

    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cost_in_credits', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('length', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('max_atmosphering_speed', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('crew', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('passengers', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cargo_capacity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('consumables', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hyperdrive_rating', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('MGLT', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('starship_class', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('starships_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.create_unique_constraint('starships_name_key', ['name'])
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('url')
        batch_op.drop_column('starship_class')
        batch_op.drop_column('MGLT')
        batch_op.drop_column('hyperdrive_rating')
        batch_op.drop_column('consumables')
        batch_op.drop_column('cargo_capacity')
        batch_op.drop_column('passengers')
        batch_op.drop_column('crew')
        batch_op.drop_column('max_atmosphering_speed')
        batch_op.drop_column('length')
        batch_op.drop_column('cost_in_credits')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('model')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_name_key', ['name'])
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('url')
        batch_op.drop_column('population')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('terrain')
        batch_op.drop_column('gravity')
        batch_op.drop_column('climate')
        batch_op.drop_column('diameter')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')

    op.create_table('planet_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gravity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('population', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planet_details_pkey'),
    sa.UniqueConstraint('planet_id', name='planet_details_planet_id_key')
    )
    op.create_table('character_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_origin', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('height', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('eye_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hair_color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transport', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='character_details_pkey'),
    sa.UniqueConstraint('character_id', name='character_details_character_id_key')
    )
    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='characters_pkey'),
    sa.UniqueConstraint('name', name='characters_name_key')
    )
    op.create_table('starship_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('starship_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cargo_capacity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('passengers', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='starship_details_pkey'),
    sa.UniqueConstraint('starship_id', name='starship_details_starship_id_key')
    )
    op.drop_table('people_vehicles')
    op.drop_table('people_starships')
    op.drop_table('people_species')
    op.drop_table('film_species')
    op.drop_table('film_people')
    op.drop_table('species')
    op.drop_table('people')
    op.drop_table('film_vehicles')
    op.drop_table('film_starships')
    op.drop_table('film_planets')
    op.drop_table('vehicles')
    op.drop_table('films')
    # ### end Alembic commands ###
